# -*- coding: utf-8 -*-
"""netfilx project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCtc070MeJ4o98rxeVnm943LjgcP-mFt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from google.colab import drive

netflix_dataset=pd.read_csv("/content/drive/MyDrive/combined_data_1.txt.zip",header=None,names=["cust_Id","rating"],usecols=[0,1])

netflix_dataset

netflix_dataset.isnull().sum()

netflix_dataset.info()

netflix_dataset.shape

movie_count=netflix_dataset.isnull().sum()

movie_count=movie_count["rating"]

movie_count

total_count=netflix_dataset["cust_Id"].nunique()

total_count

rating_count=netflix_dataset["cust_Id"].count()-movie_count

rating_count

customer_count = total_count - movie_count
customer_count

stars=netflix_dataset.groupby("rating")["rating"].agg(["count"])

stars

stars.plot(kind="barh",legend=False, figsize=(10, 5))

movie_id = None
movie_np = []

for i in netflix_dataset['cust_Id']:
  if ":" in i:
    movie_id = int(i.replace(":",""))
  movie_np.append(movie_id)

movie_np

netflix_dataset["Movie_Id"]=movie_np

netflix_dataset

netflix_dataset = netflix_dataset[netflix_dataset['rating'].notna()]

netflix_dataset.info()

netflix_dataset['Cust_Id'] = netflix_dataset['cust_Id'].astype(int)

netflix_dataset.info()

netflix_dataset["cust_Id"]

dataset_movie_summary = netflix_dataset.groupby("Movie_Id")['rating'].agg(['count'])
dataset_movie_summary

movie_benchmark = round(dataset_movie_summary['count'].quantile(0.6),0)
movie_benchmark

drop_movie_list = dataset_movie_summary[dataset_movie_summary['count'] < movie_benchmark].index

dataset_cust_summary = netflix_dataset.groupby("Cust_Id")['rating'].agg(['count'])

cust_benchmark = round(dataset_cust_summary['count'].quantile(0.6),0)

drop_cust_list = dataset_cust_summary[dataset_cust_summary['count'] < cust_benchmark].index

netflix_dataset = netflix_dataset[~netflix_dataset['Movie_Id'].isin(drop_movie_list)]
netflix_dataset = netflix_dataset[~netflix_dataset['Cust_Id'].isin(drop_cust_list)]

from surprise import Reader , Dataset , SVD
from surprise.model_selection import cross_validate

df_title =pd.read_csv("/content/drive/MyDrive/combined_data_1.txt.zip",encoding="ISO-8859-1",header=None , names=["Movie_Id" , "Year" , "Name"] , usecols=[0,1,2])

df_title

reader=Reader()

# We only work with top 100k records for quick runtime
data = Dataset.load_from_df(netflix_dataset[["Cust_Id" , "Movie_Id" , "rating"]][ :100000] ,reader)

data

model = SVD()

cross_validate(model ,data , measures=["RMSE"],cv=3)

netflix_dataset

user_rating =netflix_dataset[netflix_dataset["Cust_Id"]==1331154]
user_rating

# Make a copy of each individual customer for recommnedation
user_1331154=df_title.copy()
user_1331154

user_1331154 = user_1331154[~user_1331154["Movie_Id"].isin(drop_movie_list)]

# Prediction part
user_1331154["Estimated_Score"]= user_1331154["Movie_Id"].apply(lambda x:model.predict(1331154 ,x).est)

# Display top 5 movies with highest estimates score that user 1331154 can like ?
user_1331154.sort_values("Estimated_Score",ascending=False)

user_1331154.head(5)











